apiVersion: v1
kind: Service
metadata:
  name: nodejs-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nodejs-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000